services:
  db:
    image: postgres:16
    container_name: pr_review_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pr_review
    ports:
      - '5555:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./internal/db/migrations:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: pr_review_app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: pr_review
